# Generated by Django 3.2 on 2024-08-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Ник пользователя'),
        ),
    ]
