# Generated by Django 3.2 on 2024-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240815_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('moderator', 'moderator')], default='user', max_length=50, verbose_name='Права доступа'),
        ),
    ]
