# Generated by Django 3.2 on 2024-08-17 13:38

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240815_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='Ник пользователя'),
        ),
    ]
