# Generated by Django 3.2 on 2024-08-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240817_1838'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectuser',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_username_email'),
        ),
    ]
