USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
ROLE_MAX_LENGTH = 50
COD_MAX_LENGTH = 254

USER = 'user'
ADMIN = 'admin'
MODERATOR = 'moderator'
USER_ROLE = (
    (USER, 'user'),
    (ADMIN, 'admin'),
    (MODERATOR, 'moderator'),
)
