USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
ROLE_MAX_LENGTH = 50
COD_MAX_LENGTH = 254
USER = 'user'
ADMIN = 'admin'
MODERATOR = 'moderator'
USER_ROLE = (
    (USER, 'user'),
    (ADMIN, 'admin'),
    (MODERATOR, 'moderator'),
)
NO_USERNAMES = 'me'
LIMIT_NAME_TEXT = 256
MIN_VALUE = 1
MAX_SCOPE_VALUE = 10
CHECK_USERNAME = r'^[\w.@+-]+\Z'
