# Generated by Django 3.2 on 2024-08-23 09:29

import django.core.validators
from django.db import migrations, models
import reviews.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Нулевой год ставить недопустимо'), django.core.validators.MaxValueValidator(limit_value=reviews.utilites.current_year, message='А вы оказывается из будущего')], verbose_name='Год выпуска'),
        ),
    ]
