# Generated by Django 3.2 on 2024-08-23 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240823_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальная оценка - 1'), django.core.validators.MaxValueValidator(limit_value=10, message='Максимальная оценка - 10')], verbose_name='Оценка'),
        ),
    ]
